- name: CW2 Playbook
  hosts: localhost
  user: ubuntu

  tasks:

  - name: Create service
    shell:
      cmd: kubectl expose deployment/kube-server --type="NodePort" --port 8080 --name kube-service

  - name: Scale app
    shell:  
      cmd: kubectl scale deployments/kube-server --replicas=4
