- name: CW2 Playbook
  hosts: localhost
  user: ubuntu

  tasks:

  - name: Install minikube
    shell:
      cmd: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

  - name: File permissions
    shell:
      cmd: chmod +x minikube

  - name: Move files
    shell:
      cmd: sudo mv minikube /usr/local/bin/  

  - name: Start minikube
    shell:
      cmd: minikube start
