- name: CW2 Playbook
  hosts: localhost
  user: ubuntu

  tasks:

  - name: Pull Docker image
    shell:
      cmd: docker pull jonyward/final:1

  - name: Deploy to kubernetes
    shell:
      cmd: kubectl create deployment kube-server --image=jonyward/final:1
